Update bootprep and config overview
Cray-HPE/docs-uan pull request #36
Opened 2023-05-02 22:37 UTC by keopp-hpe

#### Summary and Scope
This PR updates the UAN configuration overview to include the set/unset nologin layers in the UAN bootprep file.  Move the initial mention of using sat bootprep to the basic config page since that's what we want users to use.

Also removed some redundant info from the overview page.

2023-05-02 23:39 UTC, darrenn-jackson requested changes
1 change to make

2023-05-02 23:39 UTC, darrenn-jackson commented on docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
> +layer in the configuration if `uan-set-nologin` and `uan-unset-nologin` are active.
Let's give this advice more gravity and make it active voice:
```suggestion
**IMPORTANT** Do not remove or reorder the first three layers. The UAN product requires these layers and this specific order. Also, keep the required `cos-application-last` layer, is as the last or second to last
layer in the configuration if `uan-set-nologin` and `uan-unset-nologin` are active.
```

2023-05-03 15:22 UTC, darrenn-jackson approved these changes

2023-05-03 15:54 UTC, alanm-hpe commented on docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
> +configurations, and BOS session templates. See [Create UAN Boot Images](Create_UAN_Boot_Images.md) for more details.
```suggestion
The preferred method of creating CFS configurations is to use the Shasta Admin Toolkit (SAT) `sat bootprep` command.  This command automates the creation of IMS images, CFS configurations, and BOS session templates. See [Create UAN Boot Images](Create_UAN_Boot_Images.md) for more details.
```
Taking out the newline

2023-05-03 15:55 UTC, alanm-hpe commented on docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
> +layer in the configuration if `uan-set-nologin` and `uan-unset-nologin` are active.
```suggestion
CFS uses configuration layers. Configuration layers allow the sharing of Ansible roles provided by other products, and by the site.  Non-root user access may be blocked during node configuration by enabling the `uan-set-nologin` and `uan-unset-nologin` configuration layers shown in the example bootprep file below. The parameterized fields are defined in a `products_vars.yml` file.

**IMPORTANT** Do not remove or reorder the first three layers. The UAN product requires these layers and this specific order. Also, keep the required `cos-application-last` layer, is as the last or second to last layer in the configuration if `uan-set-nologin` and `uan-unset-nologin` are active.
```

2023-05-03 15:56 UTC, alanm-hpe commented on docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
> +security of UANs, for example, preventing ssh out of the UAN over the NMN to NCN nodes.
```suggestion
- [`uan_hardening`](uan_hardening.md): This role configures site/customer-defined network security of UANs, for example, preventing ssh out of the UAN over the NMN to NCN nodes.
```

2023-05-03 16:10 UTC, alanm-hpe approved these changes

2023-05-03 16:28 UTC, merged