Add information on setting up HSM Node Groups for K3s
Cray-HPE/docs-uan pull request #43
Opened 2023-07-27 23:06 UTC by keopp-hpe

#### Summary and Scope
This PR adds documentation on adding UAN nodes to the necessary HSM node groups to support K3s configuration.

2023-07-28 14:30 UTC, darrenn-jackson requested changes
A bunch of small improvements.

2023-07-28 14:30 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +Before K3s can be enabled to support UAIs on Application nodes, the Application nodes must be labeled in HSM as either `k3s_server` or `k3s_agent` nodes. The UAN Ansible K3s playbooks use these label
fix typo
```suggestion
Before K3s can be enabled to support UAIs on Application nodes, the Application nodes must be labeled in HSM as either `k3s_server` or `k3s_agent` nodes. The UAN Ansible K3s playbooks use these labels to configure them. Nodes labeled `k3s_server` will become K3s control-plane (master) nodes, while nodes labeled `k3s_agent` will become K3s agent (worker) nodes available to host UAIs.
```

2023-07-28 14:30 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +When UAN software is installed or upgraded using IUF and these HSM node group labels don't exist or have no members, one Application_UAN node will be labeled `k3s_server` and the remaining nodes will
```suggestion
When UAN software is installed or upgraded using IUF and these HSM node group labels do not exist or have no members, one `Application_UAN` node type will be labeled `k3s_server` and the remaining nodes will be labeled `k3s_agent`.  If these groups exist and are not empty, IUF will not change them.
```

2023-07-28 14:30 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +If the HSM Node Group doesn't exist, this procedure may be used to create it. The group members may be provided as a comma-separated string of XNAMEs on the command line, or listed in a file.
```suggestion
If the HSM Node Group doesn't exist, the `cray hsm groups create` command can create it. The following two examples show how group members may be provided as a comma-separated string of XNAMEs on the command line, or listed in a file.
```

2023-07-28 14:30 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +This procedure is used to modify membership of an existing HSM Node Group. In these examples, GROUP_NAME would be either `k3s_server` or `k3s_agent`.
```suggestion
The `cray hsm groups members create` and `cray hsm groups members delete` commands modify membership of an existing HSM Node Group. In these examples, `GROUP_NAME` would be either `k3s_server` or `k3s_agent`.
```

2023-07-28 14:30 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +This procedure will delete the node group contained in GROUP_NAME.
```suggestion
This command deletes the node group contained in `GROUP_NAME`.
```

2023-07-28 16:16 UTC, keopp-hpe commented on docs/portal/developer-portal/hugo_toc.json
> +    "title": "Configuring a UAN for K3s (Technical Preview)",
There was a miss on my part in adding the new file further up the list.  I pushed a new commit to fix it.

2023-07-28 17:10 UTC, darrenn-jackson approved these changes

2023-07-28 21:23 UTC, alanm-hpe commented on docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
> +Before K3s can be enabled to support UAIs on Application nodes, the Application nodes must be labeled in HSM as either `k3s_server` or `k3s_agent` nodes. The UAN Ansible K3s playbooks use these label
```suggestion
Before K3s can be enabled to support UAIs on Application nodes, the Application nodes must be grouped in HSM as either `k3s_server` or `k3s_agent` nodes. The UAN Ansible K3s playbook use these groups to determine what role they will have. Nodes grouped as `k3s_server` will become K3s control-plane (master) nodes, while nodes grouped as `k3s_agent` will become K3s agent (worker) nodes.
```

2023-07-28 21:27 UTC, alanm-hpe commented
Could you add a link to https://github.com/Cray-HPE/docs-csm/blob/release/1.6/operations/configuration_management/Ansible_Inventory.md? It provides some useful information on ansible dynamic inventory and hsm groups.

2023-07-28 23:49 UTC, keopp-hpe commented
> Could you add a link to https://github.com/Cray-HPE/docs-csm/blob/release/1.6/operations/configuration_management/Ansible_Inventory.md? It provides some useful information on ansible dynamic inventory and hsm groups.
> 
> Not an actual link, but a reference to the "configuration_management/Ansible_Inventory" topic.

I added this:

**INFO:** For more information on how CFS uses HSM node groups to create Ansible host groups, see the [Cray System Management Documentation](https://cray-hpe.github.io/docs-csm). Follow the links to the `Cray System Management Administration Guide->Configuration Management->Ansible Inventory->Dynamic inventory and host groups` section.

2023-07-31 14:53 UTC, alanm-hpe approved these changes

2023-07-31 15:05 UTC, merged